always_use_return = false
annotate_untyped_fields_with_any = true
conditional_to_if = false
import_to_using = false
join_lines_based_on_source = true
normalize_line_endings = "unix"
pipe_to_function_call = false
remove_extra_newlines = true
short_to_long_function_def = false
long_to_short_function_def = false
whitespace_in_kwargs = true
whitespace_ops_in_indices = true
whitespace_typedefs = true
indent = 4
margin = 92
format_docstrings = false
align_struct_field = false
align_assignment = false
align_conditional = false
align_pair_arrow = false
align_matrix = false
trailing_comma = false
trailing_zero = true
indent_submodule = false
separate_kwargs_with_semicolon = false
surround_whereop_typeparameters = true
variable_call_indent = []
yas_style_nesting = false
disallow_single_arg_nesting = true