name = "SequentialSamplingModels"
uuid = "0e71a2a6-2b30-4447-8742-d083a85e82d1"
authors = ["itsdfish"]
version = "0.7.3"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
FunctionZeros = "b21f74c0-b399-568f-9643-d20f4fa2c814"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[weakdeps]
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[extensions]
TuringExt = "Turing"

[compat]
Distributions = "v0.24.6, 0.25"
DynamicPPL = "0.22.0,0.23.0"
FunctionZeros = "0.2.0,0.3.0"
Interpolations = "0.14.0"
KernelDensity = "0.6.5"
PrettyTables = "1.1.0, 2"
SafeTestsets = "v0.0.1,0.1.0"
SpecialFunctions = "1,2"
StatsAPI = "1.0.0"
julia = "1"

[extras]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Turing", "QuadGK", "Test", "SafeTestsets", "KernelDensity", "Interpolations", "StatsBase", "Statistics"]
