[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SSMPlots = "b9734e3f-1fb5-4b0f-895a-a4ed7ba034cc"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Colors = "0.12.0"
DataFrames = "1.0.0"
Documenter = "1"
KernelDensity = "0.6.0"
Plots = "1.0.0"
SSMPlots = "0.1.1"
StatsBase = "0.33.0,0.34.0"
StatsModels = "0.7.0"
StatsPlots = "0.15.0"
Turing = "0.26.0,0.27.0,0.28.0,0.29.0"
